version: '3.8'
services:
  bot:
    build: .
    depends_on:
      - db
    volumes:
      - ./bot:/app/bot
      - ./alembic/versions:/app/alembic/versions
    ports:
      - '8000:80'

  db:
    image: 'postgres:13'
    env_file: .env