"""change Moderations table

Revision ID: 4c931b665b4f
Revises: 4fc3ae9ba717
Create Date: 2020-07-09 22:52:00.402875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c931b665b4f'
down_revision = '4fc3ae9ba717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderations', sa.Column('moderator_id', sa.BigInteger(), nullable=True))
    op.add_column('moderations', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderations', 'reason')
    op.drop_column('moderations', 'moderator_id')
    # ### end Alembic commands ###
