"""add verification_roles table

Revision ID: 4fc3ae9ba717
Revises: 215e9036a3d7
Create Date: 2020-07-05 20:08:18.197783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc3ae9ba717'
down_revision = '215e9036a3d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('moderations', sa.Column('guild_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'moderations', 'guilds', ['guild_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moderations', type_='foreignkey')
    op.drop_column('moderations', 'guild_id')
    op.drop_table('verification_roles')
    # ### end Alembic commands ###
