"""base

Revision ID: ae12a0763d41
Revises: 
Create Date: 2020-06-07 14:39:24.381306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae12a0763d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('playlist_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id')
    )
    op.create_table('youtube_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id')
    )
    op.create_table('guild_playlists',
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['youtube_playlists.id'], )
    )
    op.create_table('playlist_videos',
    sa.Column('playlist_id', sa.BigInteger(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['youtube_playlists.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], )
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('playlist_videos')
    op.drop_table('guild_playlists')
    op.drop_table('youtube_videos')
    op.drop_table('youtube_playlists')
    op.drop_table('guilds')
    # ### end Alembic commands ###
